/*

 KANI_KOUSEN_PALATTE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 27

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define kani_kousen_palatteBank 0
/* Start of tile array. */
extern unsigned char kani_kousen_palette[];

/* End of KANI_KOUSEN_PALATTE.H */
