/*

 SICKLE_HAMMER.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\d1x13\Desktop\gbtd\palattes\sh_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define sickle_hammerWidth 20
#define sickle_hammerHeight 18
#define sickle_hammerBank 0

extern const unsigned char sickle_hammer[];

/* End of SICKLE_HAMMER.H */
