/*

 SHIP_START.H

 Map Include File.

 Info:
   Section       : x
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\home\d1x13\Desktop\gbtd\palattes\ship_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ship_startWidth 32
#define ship_startHeight 32
#define ship_startBank 0

extern unsigned char open_screen[];

/* End of SHIP_START.H */
