/*

 CHAIN_BORDER_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 9

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define chain_border_tilesBank 0
/* Start of tile array. */
extern const unsigned char chain_border_tiles[];

/* End of CHAIN_BORDER_TILES.H */
