/*

 CHAIN_BORDER.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\d1x13\Desktop\gbtd\palattes\chain_border_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define chain_borderWidth 20
#define chain_borderHeight 18
#define chain_borderBank 0

extern const unsigned char chain_border[];

/* End of CHAIN_BORDER.H */
