CC = lcc -Wa-l -Wl-m -Wl-j -DUSE_SFT_FOR_REG -Wl-yp0x143=0x80

asakawa_sir_shot.o : asakawa_air_shot.c
	$(CC) -c -o $@ $<
asakawa_front_idle.o : asakawa_front_idle.c
	$(CC) -c -o $@ $<
asakawa_walk_sideways.o : askawa_walk_sideways.c
	$(CC) -c -o $@ $<
fisherman_walk_sideways.o : fisherman_walk_sideways.c
	$(CC) -c -o $@ $<
fisherman_walk_up.o : fisherman_walk_up.c
	$(CC) -c -o $@ $<
hero_back_idle.o : hero_back_idle.c
	$(CC) -c -o $@ $<
hero_front_idle.o : hero_front_idle.c
	$(CC) -c -o $@ $<
hero_lie_down.o : hero_lie_down.c
	$(CC) -c -o $@ $<
hero_walk_down.o : hero_walk_down.c
	$(CC) -c -o $@ $<
hero_walk_sideways.o : hero_walk_sideways.c
	$(CC) -c -o $@ $<
hero_walk_up.o : hero_walk_up.c
	$(CC) -c -o $@ $<
king_crab.o : king_crab.c
	$(CC) -c -o $@ $<
norm_crab.o : norm_crab.c
	$(CC) -c -o $@ $<
student_front_idle.o : student_front_idle.c
	$(CC) -c -o $@ $<
student_idle_back.o : student_idle_back.c
	$(CC) -c -o $@ $<

clean: 
	rm -f .*.swp *.o *.lst *.map *.gb *~ *.rel *.cdb *.ihx *.lnk *.sym *.asm *.sn1


