/*

 CASTLE_TOWN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 36
   Tile set      : C:\Users\2121v\Desktop\sproj_sprites\beta_tiles.gb.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define castle townWidth 40
#define castle townHeight 36
#define castle townBank 0

extern unsigned char castle town[];

/* End of CASTLE_TOWN.H */
