/*

 ROOM1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\2121v\Desktop\sproj_sprites\beta_tiles.gb.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define room1Width 20
#define room1Height 18
#define room1Bank 0

extern unsigned char room1[];

/* End of ROOM1.H */
