/*

 GAME_OVER.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 2
   Tile set      : game_over.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define game_overWidth 10
#define game_overHeight 2
#define game_overBank 0

unsigned char game_over[] =
{
    0x00, 0x17, 0x11, 0x1d, 0x15, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x1f, 0x26, 0x15, 0x22, 0x00, 0x00, 0x00, 0x00, 0x00
};

/* End of GAME_OVER.C */
