/*

 FONT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 45

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define fontBank 0

/* CGB palette entries. */
#define fontCGB0 1
#define fontCGB1 0
#define fontCGB2 0
#define fontCGB3 0
#define fontCGB4 0
#define fontCGB5 0
#define fontCGB6 0
#define fontCGB7 0
#define fontCGB8 0
#define fontCGB9 0
#define fontCGB10 0
#define fontCGB11 0
#define fontCGB12 0
#define fontCGB13 0
#define fontCGB14 0
#define fontCGB15 0
#define fontCGB16 0
#define fontCGB17 0
#define fontCGB18 0
#define fontCGB19 0
#define fontCGB20 0
#define fontCGB21 0
#define fontCGB22 0
#define fontCGB23 0
#define fontCGB24 0
#define fontCGB25 0
#define fontCGB26 0
#define fontCGB27 0
#define fontCGB28 0
#define fontCGB29 0
#define fontCGB30 0
#define fontCGB31 0
#define fontCGB32 0
#define fontCGB33 0
#define fontCGB34 0
#define fontCGB35 0
#define fontCGB36 0
#define fontCGB37 0
#define fontCGB38 0
#define fontCGB39 0
#define fontCGB40 0
#define fontCGB41 0
#define fontCGB42 0
#define fontCGB43 0
#define fontCGB44 0
#define fontCGB45 0
/* Start of tile array. */
extern unsigned char font[];

/* End of FONT.H */
