/*

 LEVEL_1_SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\d1x13\Desktop\gbtd\palattes\level_1_screen_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level_1_screenWidth 20
#define level_1_screenHeight 18
#define level_1_screenBank 0

extern unsigned char level_1_screen[];

/* End of LEVEL_1_SCREEN.H */
