/*

 LEVEL_1_SCREEN_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 39

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define level_1_screen_tilesBank 0
/* Start of tile array. */
extern unsigned char level_1_screen_tiles[];

/* End of LEVEL_1_SCREEN_TILES.H */
