/*

 SHIT_POT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\home\d1x13\Desktop\gbtd\palattes\shit_pot_floor_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define shit_potWidth 32
#define shit_potHeight 32
#define shit_potBank 0

extern unsigned char shit_pot[];

/* End of SHIT_POT.H */
