/*

 SECOND_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 36
   Tile set      : C:\Users\2121v\Desktop\sproj_sprites\second_map.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define second_mapWidth 40
#define second_mapHeight 36
#define second_mapBank 0

extern unsigned char second_map[];

/* End of SECOND_MAP.H */
